// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnBtUnRvudQb4ePTajgD3y-HxXOkhY3vQ',
    appId: '1:388271272219:web:cbfab097265d6b3e72e3be',
    messagingSenderId: '388271272219',
    projectId: 'reflection-bda9a',
    authDomain: 'reflection-bda9a.firebaseapp.com',
    storageBucket: 'reflection-bda9a.firebasestorage.app',
    measurementId: 'G-MCB184H742',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdr5hJG5LYhHSQAshMW627ttrW0U2Ez0w',
    appId: '1:388271272219:android:15717a6d81accc1472e3be',
    messagingSenderId: '388271272219',
    projectId: 'reflection-bda9a',
    storageBucket: 'reflection-bda9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_oNntLkfmm7LPTbjW-HB-QCZ8vmm55YM',
    appId: '1:388271272219:ios:92f27c9da689173b72e3be',
    messagingSenderId: '388271272219',
    projectId: 'reflection-bda9a',
    storageBucket: 'reflection-bda9a.firebasestorage.app',
    iosBundleId: 'com.zulunity.reflection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_oNntLkfmm7LPTbjW-HB-QCZ8vmm55YM',
    appId: '1:388271272219:ios:92f27c9da689173b72e3be',
    messagingSenderId: '388271272219',
    projectId: 'reflection-bda9a',
    storageBucket: 'reflection-bda9a.firebasestorage.app',
    iosBundleId: 'com.zulunity.reflection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnBtUnRvudQb4ePTajgD3y-HxXOkhY3vQ',
    appId: '1:388271272219:web:d22609b0255738f972e3be',
    messagingSenderId: '388271272219',
    projectId: 'reflection-bda9a',
    authDomain: 'reflection-bda9a.firebaseapp.com',
    storageBucket: 'reflection-bda9a.firebasestorage.app',
    measurementId: 'G-8XWV16K87J',
  );
}
